/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.UserDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import model.User;

/**
 *
 * @author ADMIN
 */
public class ChangePassword extends javax.swing.JFrame {

    private String usernameLogin = null;
    private String pinRegex = "nhom9btl";
    private String passwordRegex = "[a-zA-Z0-9]{6,18}";

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        setLocationRelativeTo(null);
        btnUpdatePassword.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public ChangePassword(String username) {
        usernameLogin = username;
        initComponents();
        setLocationRelativeTo(null);
        btnUpdatePassword.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void clear() {
        jpwfPin.setText("");
        jpwfCurrentPassword.setText("");
        jpwfNewPassword.setText("");
        jpwfRetypeNewPassword.setText("");
        btnUpdatePassword.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void showBtnClear() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String currentPassword = String.valueOf(jpwfCurrentPassword.getPassword());
        String newPassword = String.valueOf(jpwfNewPassword.getPassword());
        String retypeNewPassword = String.valueOf(jpwfRetypeNewPassword.getPassword());
        if (!pin.equals("") || !currentPassword.equals("") || !newPassword.equals("") || !retypeNewPassword.equals("")) {
            btnClear.setEnabled(true);
        } else {
            btnClear.setEnabled(false);
        }
    }

    public void showBtnUpdatePassword() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String currentPassword = String.valueOf(jpwfCurrentPassword.getPassword());
        String newPassword = String.valueOf(jpwfNewPassword.getPassword());
        String retypeNewPassword = String.valueOf(jpwfRetypeNewPassword.getPassword());
        if (!pin.equals("") && !currentPassword.equals("") && !newPassword.equals("") && !retypeNewPassword.equals("")) {
            btnUpdatePassword.setEnabled(true);
        } else {
            btnUpdatePassword.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdatePassword = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jpwfPin = new javax.swing.JPasswordField();
        jpwfCurrentPassword = new javax.swing.JPasswordField();
        jpwfNewPassword = new javax.swing.JPasswordField();
        jpwfRetypeNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Change Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Current Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Re-type New Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        btnUpdatePassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdatePassword.setText("Update password");
        btnUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 610, -1, -1));

        jpwfPin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPinKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 410, -1));

        jpwfCurrentPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfCurrentPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfCurrentPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 410, -1));

        jpwfNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfNewPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 410, -1));

        jpwfRetypeNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfRetypeNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfRetypeNewPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfRetypeNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jpwfPinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPinKeyReleased
        // TODO add your handling code here:
        showBtnClear();
        showBtnUpdatePassword();
    }//GEN-LAST:event_jpwfPinKeyReleased

    private void jpwfCurrentPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfCurrentPasswordKeyReleased
        // TODO add your handling code here:
        showBtnClear();
        showBtnUpdatePassword();
    }//GEN-LAST:event_jpwfCurrentPasswordKeyReleased

    private void jpwfNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfNewPasswordKeyReleased
        // TODO add your handling code here:
        showBtnClear();
        showBtnUpdatePassword();
    }//GEN-LAST:event_jpwfNewPasswordKeyReleased

    private void jpwfRetypeNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfRetypeNewPasswordKeyReleased
        // TODO add your handling code here:
        showBtnClear();
        showBtnUpdatePassword();
    }//GEN-LAST:event_jpwfRetypeNewPasswordKeyReleased

    private void btnUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePasswordActionPerformed
        // TODO add your handling code here:
        String pin = String.valueOf(jpwfPin.getPassword());
        String currentPassword = String.valueOf(jpwfCurrentPassword.getPassword());
        String newPassword = String.valueOf(jpwfNewPassword.getPassword());
        String retypeNewPassword = String.valueOf(jpwfRetypeNewPassword.getPassword());
        UserDao userDao = new UserDao();
        User user = userDao.findByUsername(usernameLogin);
        if (!pin.equals(pinRegex)) {
            JOptionPane.showMessageDialog(null, "Ma PIN Khong Dung!");
            jpwfPin.setText("");
        } else if (!currentPassword.equals(user.getPassword())) {
            JOptionPane.showMessageDialog(null, "Mat Khau Cu Khong Dung!");
            jpwfCurrentPassword.setText("");
        } else if (!newPassword.matches(passwordRegex)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Phai Chua 6-18 Ky Tu Hoac So!");
            jpwfNewPassword.setText("");
            jpwfRetypeNewPassword.setText("");
        } else if (!newPassword.equals(retypeNewPassword)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Moi Khong Trung Khop!");
            jpwfNewPassword.setText("");
            jpwfRetypeNewPassword.setText("");
        } else {
            user.setPassword(newPassword);
            try {
                userDao.update(user);
                JOptionPane.showMessageDialog(null, "Thay Doi Mat Khau Thanh Cong!");
            } catch (SQLException ex) {
               
            }
        }
    }//GEN-LAST:event_btnUpdatePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jpwfCurrentPassword;
    private javax.swing.JPasswordField jpwfNewPassword;
    private javax.swing.JPasswordField jpwfPin;
    private javax.swing.JPasswordField jpwfRetypeNewPassword;
    // End of variables declaration//GEN-END:variables
}
