/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.BillDao;
import extension.OpenBillPdf;
import java.io.IOException;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Bill;

/**
 *
 * @author ADMIN
 */
public class ManageBill extends javax.swing.JFrame {
    private String usernameLogin = null;
    /**
     * Creates new form ManageBill
     */
    public ManageBill() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            showTableBill();
            double totalRevenue = getTotalRevenue();
            jlbTotalRevenue.setText("Total Revenue: " + totalRevenue);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }
    
    public ManageBill(String username) {
        initComponents();
        setLocationRelativeTo(null);
        usernameLogin = username;
        try {
            showTableBill();
            double totalRevenue = getTotalRevenue();
            jlbTotalRevenue.setText("Total Revenue: " + totalRevenue);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }

    public void showTableBill() throws SQLException {
        String customerName = jtfCustomerName.getText();
        String mobileNumber = jtfMobileNumber.getText();
        String orderDate = "";
        if (!jtfOrderDate.getText().equals("Format: yyyy-mm-dd")) {
            orderDate = jtfOrderDate.getText();
        }
        String orderTime = "";
        if (!jtfOrderTime.getText().equals("Format: hh:mm:ss")) {
            orderTime = jtfOrderTime.getText();
        }
        List<Bill> bills = new BillDao().getAllBill(customerName, mobileNumber, orderDate, orderTime);
        DefaultTableModel billModel = (DefaultTableModel) jtbBill.getModel();
        billModel.setRowCount(0);
        for (Bill temp : bills) {
            billModel.addRow(new Object[]{temp.getBillId(), temp.getCustomerName(), temp.getMobileNumber(), temp.getOrderDate(), temp.getOrderTime(), temp.getTotal()});
        }
    }
    
    public void showTableBillSort() throws SQLException {
        String customerName = jtfCustomerName.getText();
        String mobileNumber = jtfMobileNumber.getText();
        String orderDate = "";
        if (!jtfOrderDate.getText().equals("Format: yyyy-mm-dd")) {
            orderDate = jtfOrderDate.getText();
        }
        String orderTime = "";
        if (!jtfOrderTime.getText().equals("Format: hh:mm:ss")) {
            orderTime = jtfOrderTime.getText();
        }
        boolean dateTimeAsc = jrbDateTimeAsc.isSelected();
        boolean dateTimeDesc = jrbDateTimeDesc.isSelected();
        boolean totalAsc = jrbTotalAsc.isSelected();
        boolean totalDesc = jrbTotalDesc.isSelected();
        
        List<Bill> bills = new BillDao().getAllBill(customerName, mobileNumber,
                orderDate, orderTime, dateTimeAsc, dateTimeDesc, totalAsc, totalDesc);
        DefaultTableModel billModel = (DefaultTableModel) jtbBill.getModel();
        billModel.setRowCount(0);
        for (Bill temp : bills) {
            billModel.addRow(new Object[]{temp.getBillId(), temp.getCustomerName(), temp.getMobileNumber(), temp.getOrderDate(), temp.getOrderTime(), temp.getTotal()});
        }
    }

    public double getTotalRevenue() throws SQLException {
        String customerName = jtfCustomerName.getText();
        String mobileNumber = jtfMobileNumber.getText();
        String orderDate = "";
        if (!jtfOrderDate.getText().equals("Format: yyyy-mm-dd")) {
            orderDate = jtfOrderDate.getText();
        }
        String orderTime = "";
        if (!jtfOrderTime.getText().equals("Format: hh:mm:ss")) {
            orderTime = jtfOrderTime.getText();
        }
        List<Bill> bills = new BillDao().getAllBill(customerName, mobileNumber,
                orderDate, orderTime);
        double total = 0;
        for (Bill temp : bills) {
            total += temp.getTotal();
        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGr1 = new javax.swing.ButtonGroup();
        btnGr2 = new javax.swing.ButtonGroup();
        jtfOrderTime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCustomerName = new javax.swing.JTextField();
        jtfMobileNumber = new javax.swing.JTextField();
        jtfOrderDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlbTotalRevenue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jrbDateTimeAsc = new javax.swing.JRadioButton();
        jrbDateTimeDesc = new javax.swing.JRadioButton();
        jrbTotalAsc = new javax.swing.JRadioButton();
        jrbTotalDesc = new javax.swing.JRadioButton();
        btnSort = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfOrderTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfOrderTime.setText("Format: hh:mm:ss");
        jtfOrderTime.setMinimumSize(new java.awt.Dimension(210, 31));
        jtfOrderTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfOrderTimeMouseClicked(evt);
            }
        });
        jtfOrderTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfOrderTimeKeyReleased(evt);
            }
        });
        getContentPane().add(jtfOrderTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 300, -1));

        jtbBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtbBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Customer Name", "Mobile Number", "Order Date", "Order Time", "Total"
            }
        ));
        jtbBill.setMaximumSize(new java.awt.Dimension(1400, 500));
        jtbBill.setMinimumSize(new java.awt.Dimension(1400, 500));
        jtbBill.setRowHeight(40);
        jtbBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBill);
        if (jtbBill.getColumnModel().getColumnCount() > 0) {
            jtbBill.getColumnModel().getColumn(0).setMinWidth(210);
            jtbBill.getColumnModel().getColumn(0).setMaxWidth(210);
            jtbBill.getColumnModel().getColumn(1).setMinWidth(350);
            jtbBill.getColumnModel().getColumn(1).setMaxWidth(350);
            jtbBill.getColumnModel().getColumn(2).setMinWidth(210);
            jtbBill.getColumnModel().getColumn(2).setMaxWidth(210);
            jtbBill.getColumnModel().getColumn(3).setMinWidth(210);
            jtbBill.getColumnModel().getColumn(3).setMaxWidth(210);
            jtbBill.getColumnModel().getColumn(4).setMinWidth(210);
            jtbBill.getColumnModel().getColumn(4).setMaxWidth(210);
            jtbBill.getColumnModel().getColumn(5).setMinWidth(210);
            jtbBill.getColumnModel().getColumn(5).setMaxWidth(210);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 1400, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Customer Name: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mobile Number: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Order Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Order Time:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jtfCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfCustomerName.setMinimumSize(new java.awt.Dimension(210, 31));
        jtfCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCustomerNameKeyReleased(evt);
            }
        });
        getContentPane().add(jtfCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 300, -1));

        jtfMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfMobileNumber.setMinimumSize(new java.awt.Dimension(210, 31));
        jtfMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMobileNumberKeyReleased(evt);
            }
        });
        getContentPane().add(jtfMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 300, -1));

        jtfOrderDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfOrderDate.setText("Format: yyyy-mm-dd");
        jtfOrderDate.setMinimumSize(new java.awt.Dimension(210, 31));
        jtfOrderDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfOrderDateMouseClicked(evt);
            }
        });
        jtfOrderDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfOrderDateKeyReleased(evt);
            }
        });
        getContentPane().add(jtfOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Sort By");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        jlbTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTotalRevenue.setText("Total Revenue: ");
        getContentPane().add(jlbTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 760, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Date Time:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Total:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        btnGr1.add(jrbDateTimeAsc);
        jrbDateTimeAsc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jrbDateTimeAsc.setText("Ascending");
        getContentPane().add(jrbDateTimeAsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        btnGr1.add(jrbDateTimeDesc);
        jrbDateTimeDesc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jrbDateTimeDesc.setText("Decreasing");
        getContentPane().add(jrbDateTimeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, -1, -1));

        btnGr2.add(jrbTotalAsc);
        jrbTotalAsc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jrbTotalAsc.setText("Ascending");
        getContentPane().add(jrbTotalAsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, -1));

        btnGr2.add(jrbTotalDesc);
        jrbTotalDesc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jrbTotalDesc.setText("Decreasing");
        getContentPane().add(jrbTotalDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, -1, -1));

        btnSort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        getContentPane().add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        btnGr1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setText("None");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, -1, -1));

        btnGr2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setText("None");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1424, 0, -1, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1528, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Click Vao Bill Trong Bang De Xem Chi Tiet Bill");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 790, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerNameKeyReleased
        try {
            // TODO add your handling code here:
            showTableBill();
            double totalRevenue = getTotalRevenue();
            jlbTotalRevenue.setText("Total Revenue: " + totalRevenue);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }//GEN-LAST:event_jtfCustomerNameKeyReleased

    private void jtfMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMobileNumberKeyReleased
        try {
            // TODO add your handling code here:
            showTableBill();
            double totalRevenue = getTotalRevenue();
            jlbTotalRevenue.setText("Total Revenue: " + totalRevenue);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }//GEN-LAST:event_jtfMobileNumberKeyReleased

    private void jtfOrderDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfOrderDateKeyReleased
        try {
            // TODO add your handling code here:
            showTableBill();
            double totalRevenue = getTotalRevenue();
            jlbTotalRevenue.setText("Total Revenue: " + totalRevenue);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }//GEN-LAST:event_jtfOrderDateKeyReleased

    private void jtfOrderTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfOrderTimeKeyReleased
        try {
            // TODO add your handling code here:
            showTableBill();
            double totalRevenue = getTotalRevenue();
            jlbTotalRevenue.setText("Total Revenue: " + totalRevenue);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }//GEN-LAST:event_jtfOrderTimeKeyReleased

    private void jtfOrderDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfOrderDateMouseClicked
        // TODO add your handling code here:
        if (jtfOrderDate.getText().equals("Format: yyyy-mm-dd")) {
            jtfOrderDate.setText("");
        }
    }//GEN-LAST:event_jtfOrderDateMouseClicked

    private void jtfOrderTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfOrderTimeMouseClicked
        // TODO add your handling code here:
        if (jtfOrderTime.getText().equals("Format: hh:mm:ss"))
            jtfOrderTime.setText("");
    }//GEN-LAST:event_jtfOrderTimeMouseClicked

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        try {
            // TODO add your handling code here:
            showTableBillSort();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Database");
        }
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        int confirmExit = JOptionPane.showConfirmDialog(null, "Are you sure?", "Back", JOptionPane.YES_NO_OPTION);
        if (confirmExit == 0) {
            setVisible(false);
            new CoffeeWithMe(usernameLogin).setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirmLogOut = JOptionPane.showConfirmDialog(null, "Are You Sure", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirmLogOut == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jtbBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBillMouseClicked
        // TODO add your handling code here:
        int row = jtbBill.getSelectedRow();
        if(row >= 0){
            int confirm = JOptionPane.showConfirmDialog(null, "Chon", "Ban Co Muon Mo File Khong", JOptionPane.YES_NO_OPTION);
            if(confirm == 0){
                String fileBill = (String) jtbBill.getModel().getValueAt(row, 0);
                try {
                    OpenBillPdf.openFile(fileBill);
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(null, "File Khong Ton Tai!!!");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Loi Mo File!!!");
                }
            }
        }
    }//GEN-LAST:event_jtbBillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGr1;
    private javax.swing.ButtonGroup btnGr2;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbTotalRevenue;
    private javax.swing.JRadioButton jrbDateTimeAsc;
    private javax.swing.JRadioButton jrbDateTimeDesc;
    private javax.swing.JRadioButton jrbTotalAsc;
    private javax.swing.JRadioButton jrbTotalDesc;
    private javax.swing.JTable jtbBill;
    private javax.swing.JTextField jtfCustomerName;
    private javax.swing.JTextField jtfMobileNumber;
    private javax.swing.JTextField jtfOrderDate;
    private javax.swing.JTextField jtfOrderTime;
    // End of variables declaration//GEN-END:variables
}
