/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.ProductDao;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;
import model.Product;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.BillDao;
import extension.OpenBillPdf;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import model.Bill;

/**
 *
 * @author ADMIN
 */
public class PlaceOrder extends javax.swing.JFrame {

    private String usernameLogin = null;
    private String phoneNumberRegex = "0[1-9]([0-9]){8}";

    private double total;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        setLocationRelativeTo(null);
        btnAddToCart.setEnabled(false);
        btnGenerateBill.setEnabled(false);
        total = 0;
    }

    public PlaceOrder(String username) {
        initComponents();
        usernameLogin = username;
        setLocationRelativeTo(null);
        btnAddToCart.setEnabled(false);
        btnGenerateBill.setEnabled(false);
        total = 0;
    }

    public void showProduct() throws SQLException {
        List<Product> listProduct = new ProductDao().getAllProductByName(jtfSearch.getText());
        DefaultTableModel model = (DefaultTableModel) jtbProduct.getModel();
        model.setRowCount(0);
        for (Product product : listProduct) {
            model.addRow(new Object[]{product.getProductName(), product.getPrice()});
        }
    }

    public void showBtnGenerateBill() {
        String mobileNumber = jtfMobileNumber.getText();
        if (mobileNumber.matches(phoneNumberRegex) && !jtfCash.getText().equals("")) {
            try {
                double cash = Double.parseDouble(jtfCash.getText());
                if (cash - total >= 0) {
                    btnGenerateBill.setEnabled(true);
                } else {
                    btnGenerateBill.setEnabled(false);
                }
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(null, "Vui Long Nhap Dung So Tien!!!");
                jtfCash.setText("");
            }
        } else {
            btnGenerateBill.setEnabled(false);
        }
    }

    public void clear() {
        jtfCustomerName.setText("");
        jtfMobileNumber.setText("");
        jtfProductName.setText("");
        jtfPrice.setText("");
        jtfAmount.setText("");
        jtfCash.setText("");
        jpnQuantity.setValue(0);
        btnAddToCart.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCustomerName = new javax.swing.JTextField();
        jtfMobileNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfProductName = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        jtfAmount = new javax.swing.JTextField();
        jpnQuantity = new javax.swing.JSpinner();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProduct = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbBill = new javax.swing.JTable();
        btnGenerateBill = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jlbTotal = new javax.swing.JLabel();
        btnNewBill = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jtfCash = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Customer Details:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 143, -1, -1));

        jtfCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtfCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 186, 280, -1));

        jtfMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMobileNumberKeyReleased(evt);
            }
        });
        getContentPane().add(jtfMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 186, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Product");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 87, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Product Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 272, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 272, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 366, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 366, -1, -1));

        jtfProductName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtfProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 309, 200, -1));

        jtfPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 309, 100, -1));

        jtfAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtfAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 409, 100, -1));

        jpnQuantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpnQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpnQuantityStateChanged(evt);
            }
        });
        jpnQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpnQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(jpnQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 409, 200, -1));

        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 458, 200, -1));

        jtbProduct.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price"
            }
        ));
        jtbProduct.setRowHeight(40);
        jtbProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbProduct);
        if (jtbProduct.getColumnModel().getColumnCount() > 0) {
            jtbProduct.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 272, 380, 500));

        jtbBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtbBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Amount"
            }
        ));
        jtbBill.setRowHeight(40);
        jScrollPane2.setViewportView(jtbBill);
        if (jtbBill.getColumnModel().getColumnCount() > 0) {
            jtbBill.getColumnModel().getColumn(1).setMaxWidth(100);
            jtbBill.getColumnModel().getColumn(2).setMaxWidth(100);
            jtbBill.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 272, 526, 500));

        btnGenerateBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerateBill.setText("Generate Bill");
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 816, 150, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1355, 816, 150, -1));

        jlbTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTotal.setText("Total: 0");
        getContentPane().add(jlbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 241, 170, 31));

        btnNewBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNewBill.setText("New Bill");
        btnNewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1168, 816, 150, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1395, 16, -1, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1508, 16, -1, -1));

        jtfCash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCashKeyReleased(evt);
            }
        });
        getContentPane().add(jtfCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(1036, 232, 143, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Cash:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 232, -1, 31));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Search:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 235, -1, -1));

        jtfSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSearchKeyReleased(evt);
            }
        });
        getContentPane().add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 232, 312, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        String productName = jtfProductName.getText();
        String price = jtfPrice.getText();
        String quantity = String.valueOf(jpnQuantity.getValue());
        String amount = jtfAmount.getText();
        if (Integer.parseInt(quantity) > 0) {
            DefaultTableModel model = (DefaultTableModel) jtbBill.getModel();
            model.addRow(new Object[]{productName, price, quantity, amount});
            total += Double.parseDouble(amount);
            jlbTotal.setText("Total: " + total);
        } else {
            JOptionPane.showMessageDialog(null, "Vui Long Chon So Luong!");
        }
        showBtnGenerateBill();
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            // TODO add your handling code here:
            showProduct();
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
        int amount = jtbBill.getRowCount();
        if (amount != 0) {
            try {
                String mobileNumber = jtfMobileNumber.getText();
                int cnt = new BillDao().countBill(mobileNumber) + 1;
                String id = mobileNumber + "_" + cnt;
                String customerName = jtfCustomerName.getText();
                Bill bill = new Bill(id, customerName, mobileNumber, total);
                BillDao billDao = new BillDao();
                int result = billDao.save(bill);
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Tao Bill Thanh Cong!");
                    String path = "C:\\Users\\ADMIN\\Desktop\\SQL BTL JAVA\\" + id + ".pdf";
                    Document document = new Document();
                    try {
                        PdfWriter.getInstance(document, new FileOutputStream(path));
                        document.open();
                        Paragraph para = new Paragraph("----------------------------------------------------------  Receipt  -----------------------------------------------------------\n");
                        para.add("Id: " + id + "\n");
                        para.add("Customer Name: " + customerName + "\n");
                        para.add("Mobile Number: " + mobileNumber + "\n");
                        para.add("Date: " + billDao.getOrderDate(id)
                                + "  Time: " + billDao.getOrderTime(id) + "\n");
                        para.add("----------------------------------------------------------------------------------------------------------------------------------\n\n");
                        document.add(para);
                        PdfPTable ptb = new PdfPTable(4);
                        ptb.addCell("Name");
                        ptb.addCell("Price");
                        ptb.addCell("Quantity");
                        ptb.addCell("Total");
                        DefaultTableModel billModel = (DefaultTableModel) jtbBill.getModel();
                        for (int i = 0; i < jtbBill.getRowCount(); i++) {
                            ptb.addCell((String) billModel.getValueAt(i, 0));
                            ptb.addCell((String) billModel.getValueAt(i, 1));
                            ptb.addCell((String) billModel.getValueAt(i, 2));
                            ptb.addCell((String) billModel.getValueAt(i, 3));
                        }
                        document.add(ptb);
                        Paragraph sep = new Paragraph("--------------------------------"
                                                    + "---------------------------------"
                                                    + "---------------------------------"
                                                    + "--------------------------------"
                                                      );
                        document.add(sep);
                        //-------------
                        Paragraph para2 = new Paragraph("                                 "
                                + "                                 "
                                + "                                 "
                                + " Total: " + total + "\n");
                        // Add line Customer's Cash
                        para2.add("                               "
                                + "                               "
                                + "                               "
                                + "       Cash: " + jtfCash.getText() + "\n");

                        //  Add line Change for Customer
                        try {
                            para2.add("                               "
                                    + "                               "
                                    + "                               "
                                    + "       Change: " + (Double.parseDouble(jtfCash.getText()) - total));
                        } catch (NumberFormatException numberFormatException) {
                            JOptionPane.showMessageDialog(null, "Vui Long Nhap Dung So Tien!!!");
                        }

                        document.add(para2);
                        document.add(sep);
                        // End paragraph with Thank You
                        Paragraph thank = new Paragraph("---------------------------------"
                                + "-------------------------"
                                + " Thank You --------------"
                                + "-------------------------"
                                + "-----------------");
                        document.add(thank);
                    } catch (DocumentException | FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "Tao File Khong Thanh Cong!!!");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Xay Ra Loi Database!!!");
                    }
                    document.close();
                    try {
                         OpenBillPdf.openFile(id);
                    } catch (IOException ioE) {
                        JOptionPane.showMessageDialog(null, "Loi Mo File!!!");
                    } catch (IllegalArgumentException sE){
                        JOptionPane.showMessageDialog(null, "File Khong Ton Tai!!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Tao Bill Khong Thanh Cong!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Xay Ra Loi Database!!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chua Co Mat Hang!!!");
        }

    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int id = jtbBill.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jtbBill.getModel();
        if (id != -1) {
            String totalDel = (String) model.getValueAt(id, 3);
            model.removeRow(id);
            total -= Double.parseDouble(totalDel);
            jlbTotal.setText("Total: " + total);
        }
        showBtnGenerateBill();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jtbProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbProductMouseClicked
        // TODO add your handling code here:
        int index = jtbProduct.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jtbProduct.getModel();
        jtfProductName.setText((String) model.getValueAt(index, 0));
        jtfPrice.setText(String.valueOf(model.getValueAt(index, 1)));
        jpnQuantity.setValue(1);
        jtfAmount.setText(String.valueOf((int) jpnQuantity.getValue() * Double.parseDouble(jtfPrice.getText())));
        btnAddToCart.setEnabled(true);
    }//GEN-LAST:event_jtbProductMouseClicked

    private void jpnQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpnQuantityStateChanged
        // TODO add your handling code here:
        if (!jtfPrice.getText().equals("")) {
            jtfAmount.setText(String.valueOf((int) jpnQuantity.getValue() * Double.parseDouble(jtfPrice.getText())));
        }
    }//GEN-LAST:event_jpnQuantityStateChanged

    private void btnNewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBillActionPerformed
        // TODO add your handling code here:
        clear();
        DefaultTableModel billModel = (DefaultTableModel) jtbBill.getModel();
        billModel.setRowCount(0);
        btnAddToCart.setEnabled(false);
        btnGenerateBill.setEnabled(false);
        total = 0;
        jlbTotal.setText("Total: " + total);
    }//GEN-LAST:event_btnNewBillActionPerformed

    private void jtfMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMobileNumberKeyReleased
        // TODO add your handling code here:
        showBtnGenerateBill();
        String mobileNumber = jtfMobileNumber.getText();
        if (mobileNumber.matches(phoneNumberRegex)) {
            try {
                String name = new BillDao().findNameByMobileNumber(mobileNumber);
                if(name != null) jtfCustomerName.setText(name);
            } catch (SQLException ex) {
                Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jtfCustomerName.setText("");
        }
    }//GEN-LAST:event_jtfMobileNumberKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        int confirmExit = JOptionPane.showConfirmDialog(null, "Are you sure?", "Back", JOptionPane.YES_NO_OPTION);
        if (confirmExit == 0) {
            setVisible(false);
            new CoffeeWithMe(usernameLogin).setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:jtfCash
        int confirmLogOut = JOptionPane.showConfirmDialog(null, "Are You Sure", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirmLogOut == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jtfCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCashKeyReleased
        // TODO add your handling code here:
        showBtnGenerateBill();
    }//GEN-LAST:event_jtfCashKeyReleased

    private void jpnQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpnQuantityKeyReleased
        // TODO add your handling code here:
        if (!jtfPrice.getText().equals("")) {
            jtfAmount.setText(String.valueOf((int) jpnQuantity.getValue() * Double.parseDouble(jtfPrice.getText())));
        }
    }//GEN-LAST:event_jpnQuantityKeyReleased

    private void jtfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyReleased
        try {
            // TODO add your handling code here:
            showProduct();
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtfSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton btnNewBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JSpinner jpnQuantity;
    private javax.swing.JTable jtbBill;
    private javax.swing.JTable jtbProduct;
    private javax.swing.JTextField jtfAmount;
    private javax.swing.JTextField jtfCash;
    private javax.swing.JTextField jtfCustomerName;
    private javax.swing.JTextField jtfMobileNumber;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfProductName;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
