/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.UserDao;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.User;

/**
 *
 * @author ADMIN
 */
public class RecoveryAccount extends javax.swing.JFrame {

    private String pinRegex = "nhom9btl";
    private String passwordRegex = "[a-zA-Z0-9]{6,18}";

    /**
     * Creates new form RecoveryAccount
     */
    public RecoveryAccount() {
        initComponents();
        setLocationRelativeTo(null);
        btnFindYourAccount.setEnabled(false);
        btnConfirm.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void clear() {
        jpwfPin.setText("");
        jtfUsername.setText("Enter Your Username To Find Your Account!");
        jpwfPassword.setText("");
        jpwfConfirmPassword.setText("");
        btnFindYourAccount.setEnabled(false);
        btnConfirm.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void showBtnFind() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
//        String password = String.valueOf(jpwfPassword.getPassword());
//        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if (!pin.equals("") && !username.equals("") && !username.equals("Enter Your Username To Find Your Account!")) {
            btnFindYourAccount.setEnabled(true);
        } else {
            btnFindYourAccount.setEnabled(false);
        }
    }

    public void showBtnConfirm() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if (!pin.equals("") && !username.equals("") && !username.equals("Enter Your Username To Find Your Account!") && !password.equals("") && !confirmPassword.equals("")) {
            btnConfirm.setEnabled(true);
        } else {
            btnConfirm.setEnabled(false);
        }
    }

    public void showBtnClear() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if (!pin.equals("") || !confirmPassword.equals("")) {
            btnClear.setEnabled(true);
        } else if (!username.equals("") && !username.equals("Enter Your Username To Find Your Account!")) {
            btnClear.setEnabled(true);
        } else if (!password.equals("")) {
            btnClear.setEnabled(true);
        } else if (!confirmPassword.equals("")) {
            btnClear.setEnabled(true);
        } else {
            btnClear.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jtfUsername = new javax.swing.JTextField();
        jpwfPin = new javax.swing.JPasswordField();
        jpwfPassword = new javax.swing.JPasswordField();
        jpwfConfirmPassword = new javax.swing.JPasswordField();
        btnFindYourAccount = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Recovery Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 151, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 281, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 427, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Re-type New Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 501, -1, -1));

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 701, 639, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 619, 290, -1));

        jtfUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfUsername.setText("Enter Your Username To Find Your Account!");
        jtfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfUsernameMouseClicked(evt);
            }
        });
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
        });
        getContentPane().add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 350, 639, -1));

        jpwfPin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPinKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 281, 639, -1));

        jpwfPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 424, 639, -1));

        jpwfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfConfirmPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 501, 639, -1));

        btnFindYourAccount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFindYourAccount.setText("Find Your Account");
        btnFindYourAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindYourAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnFindYourAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 619, 290, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("Back To Sign In");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1199, 6, -1, 48));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1446, 6, 148, 48));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int confirmBack = JOptionPane.showConfirmDialog(null, "Are You Sure?", "Back To Sign In", JOptionPane.YES_NO_OPTION);
        if (confirmBack == 0) {
            setVisible(false);
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnFindYourAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindYourAccountActionPerformed
        // TODO add your handling code here:
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        if (!pin.equals(pinRegex)) {
            JOptionPane.showMessageDialog(null, "Ma PIN Khong Dung!!!");
            jpwfPin.setText("");
        } else {
            try {
                boolean exist = false;
                User user = new UserDao().findByUsername(username);
                if (user != null) {
                    exist = true;
                }
                if (exist) {
                    JOptionPane.showMessageDialog(null, "Vui Long Nhap Mat Khau Moi");
                } else {
                    JOptionPane.showMessageDialog(null, "Tai Khoan Khong Ton Tai");
                    jtfUsername.setText("Enter Your Username To Find Your Account!");
                }
            } catch (DateTimeParseException ex) {
                JOptionPane.showMessageDialog(null, "Da Xay Ra Loi Dinh Dang Ngay Thang!");
            }
        }
    }//GEN-LAST:event_btnFindYourAccountActionPerformed

    private void jtfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUsernameMouseClicked
        // TODO add your handling code here:
        if (jtfUsername.getText().equals("Enter Your Username To Find Your Account!")) {
            jtfUsername.setText("");
        }
    }//GEN-LAST:event_jtfUsernameMouseClicked

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpwfPinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPinKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jpwfPinKeyReleased

    private void jpwfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPasswordKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jpwfPasswordKeyReleased

    private void jpwfConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfConfirmPasswordKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jpwfConfirmPasswordKeyReleased

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if(!pin.equals(pinRegex)){
            JOptionPane.showMessageDialog(null, "Ma Pin Khong Dung!");
            jpwfPin.setText("");
        } else if (!password.matches(passwordRegex)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Phai Chua 6-18 Ky Tu Hoac So!");
            jpwfPassword.setText("");
            jpwfConfirmPassword.setText("");
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Khong Trung Khop");
            jpwfConfirmPassword.setText("");
        } else {
            try {
                UserDao userDao = new UserDao();
                User user = userDao.findByUsername(username);
                if (user != null) {
                    user.setPassword(password);
                    userDao.update(user);
                    JOptionPane.showMessageDialog(null, "Thay Doi Mat Khau Thanh Cong");
                } else {
                    JOptionPane.showMessageDialog(null, "Tai Khoan Khong Ton Tai!!!");
                    jtfUsername.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Xay Ra Loi Database!!!");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Xay Ra Loi Dinh Dang Ngay Thang!!!");
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirmLogOut = JOptionPane.showConfirmDialog(null, "Are You Sure", "Exit", JOptionPane.YES_NO_OPTION);
        if(confirmLogOut == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFindYourAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jpwfConfirmPassword;
    private javax.swing.JPasswordField jpwfPassword;
    private javax.swing.JPasswordField jpwfPin;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
