/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.UserDao;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.User;

/**
 *
 * @author ADMIN
 */
public class RecoveryAccount extends javax.swing.JFrame {

    private String pinRegex = "nhom9btl";
    private String passwordRegex = "[a-zA-Z0-9]{6,18}";

    /**
     * Creates new form RecoveryAccount
     */
    public RecoveryAccount() {
        initComponents();
        btnFindYourAccount.setEnabled(false);
        btnConfirm.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void clear() {
        jpwfPin.setText("");
        jtfUsername.setText("Enter Your Username To Find Your Account!");
        jpwfPassword.setText("");
        jpwfConfirmPassword.setText("");
        btnFindYourAccount.setEnabled(false);
        btnConfirm.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void showBtnFind() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
//        String password = String.valueOf(jpwfPassword.getPassword());
//        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if (!pin.equals("") && !username.equals("") && !username.equals("Enter Your Username To Find Your Account!")) {
            btnFindYourAccount.setEnabled(true);
        } else {
            btnFindYourAccount.setEnabled(false);
        }
    }

    public void showBtnConfirm() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if (!pin.equals("") && !username.equals("") && !username.equals("Enter Your Username To Find Your Account!") && !password.equals("") && !confirmPassword.equals("")) {
            btnConfirm.setEnabled(true);
        } else {
            btnConfirm.setEnabled(false);
        }
    }

    public void showBtnClear() {
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if (!pin.equals("") || !confirmPassword.equals("")) {
            btnClear.setEnabled(true);
        } else if (!username.equals("") && !username.equals("Enter Your Username To Find Your Account!")) {
            btnClear.setEnabled(true);
        } else if (!password.equals("")) {
            btnClear.setEnabled(true);
        } else if (!confirmPassword.equals("")) {
            btnClear.setEnabled(true);
        } else {
            btnClear.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jtfUsername = new javax.swing.JTextField();
        jpwfPin = new javax.swing.JPasswordField();
        jpwfPassword = new javax.swing.JPasswordField();
        jpwfConfirmPassword = new javax.swing.JPasswordField();
        btnFindYourAccount = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Recovery Account");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PIN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password");

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jtfUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfUsername.setText("Enter Your Username To Find Your Account!");
        jtfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfUsernameMouseClicked(evt);
            }
        });
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
        });

        jpwfPin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPinKeyReleased(evt);
            }
        });

        jpwfPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPasswordKeyReleased(evt);
            }
        });

        jpwfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfConfirmPasswordKeyReleased(evt);
            }
        });

        btnFindYourAccount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFindYourAccount.setText("Find Your Account");
        btnFindYourAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindYourAccountActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Back To Sign In");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(699, 699, 699))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFindYourAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(212, 212, 212)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jpwfPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jpwfPin, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jpwfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpwfPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jpwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jpwfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindYourAccount)
                    .addComponent(btnClear))
                .addGap(44, 44, 44)
                .addComponent(btnConfirm)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int confirmBack = JOptionPane.showConfirmDialog(null, "Are You Sure?", "Back To Sign In", JOptionPane.YES_NO_OPTION);
        if (confirmBack == 0) {
            setVisible(false);
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnFindYourAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindYourAccountActionPerformed
        // TODO add your handling code here:
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        if (!pin.equals(pinRegex)) {
            JOptionPane.showMessageDialog(null, "Ma PIN Khong Dung!!!");
            jpwfPin.setText("");
        } else {
            boolean exist = false;
            User user = new UserDao().findByUsername(username);
            if (user != null) {
                exist = true;
            }
            if (exist) {
                JOptionPane.showMessageDialog(null, "Vui Long Nhap Mat Khau Moi");
            } else {
                JOptionPane.showMessageDialog(null, "Tai Khoan Khong Ton Tai");
                jtfUsername.setText("Enter Your Username To Find Your Account!");
            }
        }
    }//GEN-LAST:event_btnFindYourAccountActionPerformed

    private void jtfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUsernameMouseClicked
        // TODO add your handling code here:
        if (jtfUsername.getText().equals("Enter Your Username To Find Your Account!")) {
            jtfUsername.setText("");
        }
    }//GEN-LAST:event_jtfUsernameMouseClicked

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpwfPinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPinKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jpwfPinKeyReleased

    private void jpwfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPasswordKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jpwfPasswordKeyReleased

    private void jpwfConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfConfirmPasswordKeyReleased
        // TODO add your handling code here:
        showBtnFind();
        showBtnConfirm();
        showBtnClear();
    }//GEN-LAST:event_jpwfConfirmPasswordKeyReleased

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String pin = String.valueOf(jpwfPin.getPassword());
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        if(!pin.equals(pinRegex)){
            JOptionPane.showMessageDialog(null, "Ma Pin Khong Dung!");
            jpwfPin.setText("");
        } else if (!password.matches(passwordRegex)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Phai Chua 6-18 Ky Tu Hoac So!");
            jpwfPassword.setText("");
            jpwfConfirmPassword.setText("");
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Khong Trung Khop");
            jpwfConfirmPassword.setText("");
        } else {
            try {
                UserDao userDao = new UserDao();
                User user = userDao.findByUsername(username);
                if (user != null) {
                    user.setPassword(password);
                    userDao.update(user);
                    JOptionPane.showMessageDialog(null, "Thay Doi Mat Khau Thanh Cong");
                } else {
                    JOptionPane.showMessageDialog(null, "Tai Khoan Khong Ton Tai!!!");
                    jtfUsername.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(RecoveryAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFindYourAccount;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jpwfConfirmPassword;
    private javax.swing.JPasswordField jpwfPassword;
    private javax.swing.JPasswordField jpwfPin;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
