/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.UserDao;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import model.User;

/**
 *
 * @author ADMIN
 */
public class SignUp extends javax.swing.JFrame {

    private String pinRegex = "nhom9btl";
    private String dateOfBirthRegex = "\\d\\d/\\d\\d/\\d\\d\\d\\d";
    private String usernameRegex = "[a-zA-Z0-9]{6,18}";
    private String passwordRegex = "[a-zA-Z0-9]{6,18}";
    private String phoneNumberRegex = "0([1-9]){9}";

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        btnRegister.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void clear() {
        jtfUsername.setText("");
        jpwfPassword.setText("");
        jpwfConfirmPassword.setText("");
        jtfFullName.setText("");
        jtfDateOfBirth.setText("Format: dd/MM/yyyy");
        jtfAddress.setText("");
        jtfPhoneNumber.setText("Ex: 0123456789");
        jpwfPin.setText("");
        btnRegister.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void showBtnRegister() {
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        String fullName = jtfFullName.getText();
        String dateOfBirth = jtfDateOfBirth.getText();
        String address = jtfAddress.getText();
        String phoneNumber = jtfPhoneNumber.getText();
        String pin = String.valueOf(jpwfPin.getPassword());
        if (!confirmPassword.equals("") && !username.equals("") && !password.equals("") && !fullName.equals("") && !dateOfBirth.equals("") && !address.equals("") && !phoneNumber.equals("") && !phoneNumber.equals("Ex: 0123456789") && !dateOfBirth.equals("Format: dd/MM/yyyy") && !pin.equals("")) {
            btnRegister.setEnabled(true);
        } else {
            btnRegister.setEnabled(false);
        }
    }

    public void showBtnClear() {
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        String fullName = jtfFullName.getText();
        String dateOfBirth = jtfDateOfBirth.getText();
        String address = jtfAddress.getText();
        String phoneNumber = jtfPhoneNumber.getText();
        String pin = String.valueOf(jpwfPin.getPassword());
        if (!username.equals("")) {
            btnClear.setEnabled(true);
        } else if (!password.equals("")) {
            btnClear.setEnabled(true);
        } else if (!fullName.equals("")) {
            btnClear.setEnabled(true);
        } else if (!dateOfBirth.equals("") && !dateOfBirth.equals("Format: dd/MM/yyyy")) {
            btnClear.setEnabled(true);
        } else if (!address.equals("")) {
            btnClear.setEnabled(true);
        } else if (!phoneNumber.equals("") && !phoneNumber.equals("Ex: 0123456789")) {
            btnClear.setEnabled(true);
        } else if (!confirmPassword.equals("")) {
            btnClear.setEnabled(true);
        } else if (!pin.equals("")) {
            btnClear.setEnabled(true);
        } else {
            btnClear.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jtfFullName = new javax.swing.JTextField();
        jtfDateOfBirth = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfPhoneNumber = new javax.swing.JTextField();
        jpwfPassword = new javax.swing.JPasswordField();
        jpwfConfirmPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jpwfPin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Sign Up");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Full Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Date Of Birth");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number");

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setText("Back To Sign In");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password");

        jtfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyTyped(evt);
            }
        });

        jtfFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFullNameKeyReleased(evt);
            }
        });

        jtfDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfDateOfBirth.setText("Format: dd/MM/yyyy");
        jtfDateOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfDateOfBirthMouseClicked(evt);
            }
        });
        jtfDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDateOfBirthActionPerformed(evt);
            }
        });
        jtfDateOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDateOfBirthKeyReleased(evt);
            }
        });

        jtfAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAddressActionPerformed(evt);
            }
        });
        jtfAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAddressKeyReleased(evt);
            }
        });

        jtfPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfPhoneNumber.setText("Ex: 0123456789");
        jtfPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfPhoneNumberMouseClicked(evt);
            }
        });
        jtfPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhoneNumberActionPerformed(evt);
            }
        });
        jtfPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPhoneNumberKeyReleased(evt);
            }
        });

        jpwfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpwfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPasswordKeyReleased(evt);
            }
        });

        jpwfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpwfConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfConfirmPasswordKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("PIN");

        jpwfPin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPinKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jtfUsername))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnRegister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpwfPassword)
                            .addComponent(jpwfConfirmPassword)
                            .addComponent(jtfFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfDateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpwfPin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jpwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jpwfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jpwfPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnClear))
                .addGap(70, 70, 70))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jpwfConfirmPassword, jpwfPassword, jpwfPin, jtfAddress, jtfDateOfBirth, jtfFullName, jtfPhoneNumber, jtfUsername});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDateOfBirthActionPerformed

    private void jtfPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhoneNumberActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirmExit = JOptionPane.showConfirmDialog(null, "Are you sure?", "Back To Sign In", JOptionPane.YES_NO_OPTION);
        if (confirmExit == 0) {
            setVisible(false);
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jtfDateOfBirthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfDateOfBirthMouseClicked
        // TODO add your handling code here:
        if (jtfDateOfBirth.getText().equals("Format: dd/MM/yyyy"))
            jtfDateOfBirth.setText("");
    }//GEN-LAST:event_jtfDateOfBirthMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        String fullName = jtfFullName.getText();
        String dateOfBirth = jtfDateOfBirth.getText();
        String address = jtfAddress.getText();
        String phoneNumber = jtfPhoneNumber.getText();
        String pin = String.valueOf(jpwfPin.getPassword());
        if (!username.matches(usernameRegex)) {
            JOptionPane.showMessageDialog(null, "Tai Khoan Phai Chua 6-18 Ky Tu Hoac So!");
            jtfUsername.setText("");
        } else if (!password.matches(passwordRegex)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Phai Chua 6-18 Ky Tu Hoac So!");
            jpwfPassword.setText("");
            jpwfConfirmPassword.setText("");
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Khong Trung Khop!");
            jpwfConfirmPassword.setText("");
        } else if (!dateOfBirth.matches(dateOfBirthRegex)) {
            JOptionPane.showMessageDialog(null, "Ngay Sinh Khong Dung Dinh Dang!");
            jtfDateOfBirth.setText("");
        } else if (!phoneNumber.matches(phoneNumberRegex)) {
            JOptionPane.showMessageDialog(null, "So Dien Thoai Khong Dung Dinh Dang!");
            jtfPhoneNumber.setText("");
        } else if (!pin.equals(pinRegex)) {
            JOptionPane.showMessageDialog(null, "Ma PIN Khong Dung!");
            jpwfPin.setText("");
        } else {
            User user = new User(username, password, fullName, dateOfBirth, address, phoneNumber);
            UserDao userDao = new UserDao();
            try {
                int result = userDao.save(user);
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Tao Tai Khoan Thanh Cong");
                } else {
                    JOptionPane.showMessageDialog(null, "Tai Khoan Da Ton Tai");
                    jtfUsername.setText("");
                }
            } catch (SQLException ex) {
            }
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jtfUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameKeyTyped

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpwfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPasswordKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jpwfPasswordKeyReleased

    private void jpwfConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfConfirmPasswordKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jpwfConfirmPasswordKeyReleased

    private void jtfFullNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFullNameKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfFullNameKeyReleased

    private void jtfDateOfBirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDateOfBirthKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfDateOfBirthKeyReleased

    private void jtfAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAddressKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfAddressKeyReleased

    private void jtfPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhoneNumberKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfPhoneNumberKeyReleased

    private void jtfPhoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfPhoneNumberMouseClicked
        // TODO add your handling code here:
        if (jtfPhoneNumber.getText().equals("Ex: 0123456789"))
            jtfPhoneNumber.setText("");
    }//GEN-LAST:event_jtfPhoneNumberMouseClicked

    private void jtfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddressActionPerformed

    private void jpwfPinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPinKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jpwfPinKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jpwfConfirmPassword;
    private javax.swing.JPasswordField jpwfPassword;
    private javax.swing.JPasswordField jpwfPin;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfDateOfBirth;
    private javax.swing.JTextField jtfFullName;
    private javax.swing.JTextField jtfPhoneNumber;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
