/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import dao.UserDao;
import java.sql.*;
import java.text.ParseException;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import model.User;

/**
 *
 * @author ADMIN
 */
public class SignUp extends javax.swing.JFrame {

    private String pinRegex = "nhom9btl";
    private String dateOfBirthRegex = "[0-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]";
    private String usernameRegex = "[a-zA-Z0-9]{6,18}";
    private String passwordRegex = "[a-zA-Z0-9]{6,18}";
    private String phoneNumberRegex = "0[1-9]([0-9]){8}";

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
        btnRegister.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void clear() {
        jtfUsername.setText("");
        jpwfPassword.setText("");
        jpwfConfirmPassword.setText("");
        jtfFullName.setText("");
        jtfDateOfBirth.setText("Format: yyyy-MM-dd");
        jtfAddress.setText("");
        jtfPhoneNumber.setText("Ex: 0123456789");
        jpwfPin.setText("");
        btnRegister.setEnabled(false);
        btnClear.setEnabled(false);
    }

    public void showBtnRegister() {
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        String fullName = jtfFullName.getText();
        String dateOfBirth = jtfDateOfBirth.getText();
        String address = jtfAddress.getText();
        String phoneNumber = jtfPhoneNumber.getText();
        String pin = String.valueOf(jpwfPin.getPassword());
        if (!confirmPassword.equals("") && !username.equals("") && !password.equals("") && !fullName.equals("") && !dateOfBirth.equals("") && !address.equals("") && !phoneNumber.equals("") && !phoneNumber.equals("Ex: 0123456789") && !dateOfBirth.equals("Format: yyyy-MM-dd") && !pin.equals("")) {
            btnRegister.setEnabled(true);
        } else {
            btnRegister.setEnabled(false);
        }
    }

    public void showBtnClear() {
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        String fullName = jtfFullName.getText();
        String dateOfBirth = jtfDateOfBirth.getText();
        String address = jtfAddress.getText();
        String phoneNumber = jtfPhoneNumber.getText();
        String pin = String.valueOf(jpwfPin.getPassword());
        if (!username.equals("")) {
            btnClear.setEnabled(true);
        } else if (!password.equals("")) {
            btnClear.setEnabled(true);
        } else if (!fullName.equals("")) {
            btnClear.setEnabled(true);
        } else if (!dateOfBirth.equals("") && !dateOfBirth.equals("Format: yyyy-MM-dd")) {
            btnClear.setEnabled(true);
        } else if (!address.equals("")) {
            btnClear.setEnabled(true);
        } else if (!phoneNumber.equals("") && !phoneNumber.equals("Ex: 0123456789")) {
            btnClear.setEnabled(true);
        } else if (!confirmPassword.equals("")) {
            btnClear.setEnabled(true);
        } else if (!pin.equals("")) {
            btnClear.setEnabled(true);
        } else {
            btnClear.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jtfFullName = new javax.swing.JTextField();
        jtfDateOfBirth = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfPhoneNumber = new javax.swing.JTextField();
        jpwfPassword = new javax.swing.JPasswordField();
        jpwfConfirmPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jpwfPin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 123, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 225, 153, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 153, 31));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 421, 153, 31));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Date Of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 487, 153, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 536, 153, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 585, 153, 31));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 733, 150, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1067, 733, 150, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setText("Back To Sign In");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 6, 220, 39));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Re-type New Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 354, -1, 31));

        jtfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyTyped(evt);
            }
        });
        getContentPane().add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 225, 612, -1));

        jtfFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFullNameKeyReleased(evt);
            }
        });
        getContentPane().add(jtfFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 421, 612, -1));

        jtfDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfDateOfBirth.setText("Format: yyyy-MM-dd");
        jtfDateOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfDateOfBirthMouseClicked(evt);
            }
        });
        jtfDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDateOfBirthActionPerformed(evt);
            }
        });
        jtfDateOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDateOfBirthKeyReleased(evt);
            }
        });
        getContentPane().add(jtfDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 487, 612, -1));

        jtfAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAddressActionPerformed(evt);
            }
        });
        jtfAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAddressKeyReleased(evt);
            }
        });
        getContentPane().add(jtfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 536, 612, -1));

        jtfPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfPhoneNumber.setText("Ex: 0123456789");
        jtfPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfPhoneNumberMouseClicked(evt);
            }
        });
        jtfPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhoneNumberActionPerformed(evt);
            }
        });
        jtfPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPhoneNumberKeyReleased(evt);
            }
        });
        getContentPane().add(jtfPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 585, 612, -1));

        jpwfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpwfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 290, 612, -1));

        jpwfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpwfConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfConfirmPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 354, 612, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("PIN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 634, 153, 31));

        jpwfPin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jpwfPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpwfPinKeyReleased(evt);
            }
        });
        getContentPane().add(jpwfPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 634, 612, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1463, 6, 131, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDateOfBirthActionPerformed

    private void jtfPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhoneNumberActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirmExit = JOptionPane.showConfirmDialog(null, "Are you sure?", "Back To Sign In", JOptionPane.YES_NO_OPTION);
        if (confirmExit == 0) {
            setVisible(false);
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jtfDateOfBirthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfDateOfBirthMouseClicked
        // TODO add your handling code here:
        if (jtfDateOfBirth.getText().equals("Format: yyyy-MM-dd"))
            jtfDateOfBirth.setText("");
    }//GEN-LAST:event_jtfDateOfBirthMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username = jtfUsername.getText();
        String password = String.valueOf(jpwfPassword.getPassword());
        String confirmPassword = String.valueOf(jpwfConfirmPassword.getPassword());
        String fullName = jtfFullName.getText();
        String dateOfBirth = jtfDateOfBirth.getText();
        String address = jtfAddress.getText();
        String phoneNumber = jtfPhoneNumber.getText();
        String pin = String.valueOf(jpwfPin.getPassword());
        if (!username.matches(usernameRegex)) {
            JOptionPane.showMessageDialog(null, "Tai Khoan Phai Chua 6-18 Ky Tu Hoac So!");
            jtfUsername.setText("");
        } else if (!password.matches(passwordRegex)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Phai Chua 6-18 Ky Tu Hoac So!");
            jpwfPassword.setText("");
            jpwfConfirmPassword.setText("");
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Mat Khau Khong Trung Khop!");
            jpwfConfirmPassword.setText("");
        } else if (!phoneNumber.matches(phoneNumberRegex)) {
            JOptionPane.showMessageDialog(null, "So Dien Thoai Khong Dung Dinh Dang!");
            jtfPhoneNumber.setText("");
        } else if (!pin.equals(pinRegex)) {
            JOptionPane.showMessageDialog(null, "Ma PIN Khong Dung!");
            jpwfPin.setText("");
        } else {
            try {
                User user = new User(username, password, fullName, dateOfBirth, address, phoneNumber);
                UserDao userDao = new UserDao();
                int result = userDao.save(user);
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Tao Tai Khoan Thanh Cong");
                } else {
                    JOptionPane.showMessageDialog(null, "Tai Khoan Da Ton Tai");
                    jtfUsername.setText("");
                    btnRegister.setEnabled(false);
                }
            } catch (DateTimeParseException ex) {
                JOptionPane.showMessageDialog(null, "Vui Nhap Nhap Ngay Sinh Dung Dinh Dang!");
                jtfDateOfBirth.setText("Format: yyyy-MM-dd");
                btnRegister.setEnabled(false);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Xay Ra Loi Database!");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Xay Ra Loi Dinh Dang Cua Ngay Sinh!");
            }
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jtfUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameKeyTyped

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpwfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPasswordKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jpwfPasswordKeyReleased

    private void jpwfConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfConfirmPasswordKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jpwfConfirmPasswordKeyReleased

    private void jtfFullNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFullNameKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfFullNameKeyReleased

    private void jtfDateOfBirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDateOfBirthKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfDateOfBirthKeyReleased

    private void jtfAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAddressKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfAddressKeyReleased

    private void jtfPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhoneNumberKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jtfPhoneNumberKeyReleased

    private void jtfPhoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfPhoneNumberMouseClicked
        // TODO add your handling code here:
        if (jtfPhoneNumber.getText().equals("Ex: 0123456789"))
            jtfPhoneNumber.setText("");
    }//GEN-LAST:event_jtfPhoneNumberMouseClicked

    private void jtfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddressActionPerformed

    private void jpwfPinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwfPinKeyReleased
        // TODO add your handling code here:
        showBtnRegister();
        showBtnClear();
    }//GEN-LAST:event_jpwfPinKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirmLogOut = JOptionPane.showConfirmDialog(null, "Are You Sure", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirmLogOut == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField jpwfConfirmPassword;
    private javax.swing.JPasswordField jpwfPassword;
    private javax.swing.JPasswordField jpwfPin;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfDateOfBirth;
    private javax.swing.JTextField jtfFullName;
    private javax.swing.JTextField jtfPhoneNumber;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
